name = "Project"
defaultTargets = ["Project"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.22.0-rc4"

[[lean_lib]]
name = "Project"
